// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/tns.proto

package tns

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command_CMD int32

const (
	Command_RECORD_REQUEST Command_CMD = 0
	Command_ZONE_REQUEST   Command_CMD = 1
	Command_ECHO           Command_CMD = 2
)

var Command_CMD_name = map[int32]string{
	0: "RECORD_REQUEST",
	1: "ZONE_REQUEST",
	2: "ECHO",
}

var Command_CMD_value = map[string]int32{
	"RECORD_REQUEST": 0,
	"ZONE_REQUEST":   1,
	"ECHO":           2,
}

func (x Command_CMD) String() string {
	return proto.EnumName(Command_CMD_name, int32(x))
}

func (Command_CMD) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7058b6534ae0b447, []int{0, 0}
}

type Command struct {
	// this indicates the particular command being ran against the tns daemon
	Cmd Command_CMD `protobuf:"varint,1,opt,name=cmd,proto3,enum=tns.Command_CMD" json:"cmd,omitempty"`
	// if not authoritative, we do a recursive lookup
	// a recursive lookup is defined as talking to the P2P network at large
	// for an answer. This would mean that for IPNS records, it would involve
	// talking to the rest of the network for an answer.
	//
	// if a request is authoritative, we will then retrieve the answer directly
	// from the publisher. This means sending a query to the tns daemon running
	// on the node that published the request.
	Authoritative        bool     `protobuf:"varint,2,opt,name=authoritative,proto3" json:"authoritative,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_7058b6534ae0b447, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCmd() Command_CMD {
	if m != nil {
		return m.Cmd
	}
	return Command_RECORD_REQUEST
}

func (m *Command) GetAuthoritative() bool {
	if m != nil {
		return m.Authoritative
	}
	return false
}

type Protocol struct {
	Named                string   `protobuf:"bytes,1,opt,name=named,proto3" json:"named,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Protocol) Reset()         { *m = Protocol{} }
func (m *Protocol) String() string { return proto.CompactTextString(m) }
func (*Protocol) ProtoMessage()    {}
func (*Protocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_7058b6534ae0b447, []int{1}
}

func (m *Protocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Protocol.Unmarshal(m, b)
}
func (m *Protocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Protocol.Marshal(b, m, deterministic)
}
func (m *Protocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Protocol.Merge(m, src)
}
func (m *Protocol) XXX_Size() int {
	return xxx_messageInfo_Protocol.Size(m)
}
func (m *Protocol) XXX_DiscardUnknown() {
	xxx_messageInfo_Protocol.DiscardUnknown(m)
}

var xxx_messageInfo_Protocol proto.InternalMessageInfo

func (m *Protocol) GetNamed() string {
	if m != nil {
		return m.Named
	}
	return ""
}

func (m *Protocol) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterEnum("tns.Command_CMD", Command_CMD_name, Command_CMD_value)
	proto.RegisterType((*Command)(nil), "tns.Command")
	proto.RegisterType((*Protocol)(nil), "tns.Protocol")
}

func init() { proto.RegisterFile("pb/tns.proto", fileDescriptor_7058b6534ae0b447) }

var fileDescriptor_7058b6534ae0b447 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0xd2, 0x2f,
	0xc9, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0xc9, 0x2b, 0x56, 0xea, 0x62,
	0xe4, 0x62, 0x77, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x11, 0x52, 0xe2, 0x62, 0x4e, 0xce, 0x4d,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x12, 0xd0, 0x03, 0xa9, 0x84, 0x4a, 0xe9, 0x39, 0xfb,
	0xba, 0x04, 0x81, 0x24, 0x85, 0x54, 0xb8, 0x78, 0x13, 0x4b, 0x4b, 0x32, 0xf2, 0x8b, 0x32, 0x4b,
	0x12, 0x4b, 0x32, 0xcb, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x82, 0x50, 0x05, 0x95, 0x4c,
	0xb9, 0x98, 0x9d, 0x7d, 0x5d, 0x84, 0x84, 0xb8, 0xf8, 0x82, 0x5c, 0x9d, 0xfd, 0x83, 0x5c, 0xe2,
	0x83, 0x5c, 0x03, 0x43, 0x5d, 0x83, 0x43, 0x04, 0x18, 0x84, 0x04, 0xb8, 0x78, 0xa2, 0xfc, 0xfd,
	0x5c, 0xe1, 0x22, 0x8c, 0x42, 0x1c, 0x5c, 0x2c, 0xae, 0xce, 0x1e, 0xfe, 0x02, 0x4c, 0x4a, 0x56,
	0x5c, 0x1c, 0x01, 0x20, 0xa7, 0x25, 0xe7, 0xe7, 0x08, 0x89, 0x70, 0xb1, 0xe6, 0x25, 0xe6, 0xa6,
	0x42, 0x9c, 0xc3, 0x19, 0x04, 0xe1, 0x08, 0x49, 0x70, 0xb1, 0x97, 0xa5, 0x16, 0x15, 0x67, 0xe6,
	0xe7, 0x81, 0x2d, 0xe6, 0x0c, 0x82, 0x71, 0x93, 0xd8, 0xc0, 0x9e, 0x32, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x0a, 0x22, 0x98, 0x12, 0xe4, 0x00, 0x00, 0x00,
}
